name: Build & Test
on: [push]

jobs:
  build:
    runs-on: [self-hosted]

    steps:
      - uses: actions/checkout@v4.1.4
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.22'
      - name: Install dependencies
        run: go get .
      - name: Build
        run: go build main.go
      - name: Test with the Go CLI
        run: go test main.go
