name: GoReleaser

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build_linux:
    name: Build for Linux
    runs-on: ubuntu-latest

    steps:
      - name: Check out code into the Go module directory
        uses: actions/checkout@v4.1.4
        with:
          fetch-depth: 0 # See: https://goreleaser.com/ci/actions/

      - name: Set up Go 1.22
        uses: actions/setup-go@v5
        with:
          go-version: 1.22
        id: go

      - name: Run GoReleaser for Linux
        uses: goreleaser/goreleaser-action@v5.0.0
        with:
          version: latest
          args: release --clean
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  build_windows:
    name: Build for Windows
    runs-on: windows-latest

    steps:
      - name: Check out code into the Go module directory
        uses: actions/checkout@v4.1.4
        with:
          fetch-depth: 0 # See: https://goreleaser.com/ci/actions/

      - name: Set up Go 1.22
        uses: actions/setup-go@v5
        with:
          go-version: 1.22
        id: go

      - name: Run GoReleaser for Windows
        uses: goreleaser/goreleaser-action@v5.0.0
        with:
          version: latest
          args: release --clean
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
