name: Makefile
on: [push]

jobs:
  build:
    runs-on: [self-hosted]

    steps:
      - uses: actions/checkout@v4.1.1
      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.22'
      - name: Install dependencies
        run: go get .
      - name: Build Go Project
        run: make build
